import "./globals.css";
import { Inter } from "next/font/google";
import SavedContextProvider from "../../context/forSavedContenxt";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SavedContextProvider>
      <body className={inter.className}>{children}</body>
      </SavedContextProvider>     
    </html>
  );
}
